# Generated by Django 5.2.16 on 2026-07-20 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("ts", models.DateTimeField()),
                ("severity", models.CharField(max_length=10)),
                ("kind", models.CharField(max_length=60)),
                ("message", models.CharField(max_length=400)),
                ("dedupe_key", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=60)),
                ("subject", models.CharField(max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=400)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("lesson_id", models.CharField(max_length=40, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("body_md", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=300, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("section", models.CharField(default="reports", max_length=40)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("trade_id", models.CharField(max_length=120, unique=True)),
                ("strategy", models.CharField(max_length=40)),
                ("pair", models.CharField(max_length=12)),
                ("side", models.CharField(max_length=6)),
                ("qty", models.FloatField(null=True)),
                ("entry", models.FloatField(null=True)),
                ("exit", models.FloatField(null=True)),
                ("sl", models.FloatField(null=True)),
                ("tp", models.FloatField(null=True)),
                ("pnl", models.FloatField(null=True)),
                ("pnl_r", models.FloatField(null=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("opened_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("mode", models.CharField(default="paper", max_length=10)),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="VpsHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("ts", models.DateTimeField()),
                ("uptime_s", models.BigIntegerField(null=True)),
                ("latency_ms", models.FloatField(null=True)),
                ("clock_drift_ms", models.FloatField(null=True)),
                ("disk_free_pct", models.FloatField(null=True)),
                ("mem_free_pct", models.FloatField(null=True)),
                ("feed_freshness", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("cycle", models.CharField(max_length=40)),
                ("exp_id", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=300)),
                ("verdict", models.CharField(max_length=300)),
                (
                    "report_path",
                    models.CharField(blank=True, default="", max_length=300),
                ),
            ],
            options={
                "unique_together": {("cycle", "exp_id")},
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("model_id", models.CharField(max_length=60)),
                ("version", models.CharField(default="v1.0", max_length=20)),
                ("model_class", models.CharField(default="strategy", max_length=30)),
                ("status", models.CharField(max_length=40)),
                ("oos_proof", models.CharField(blank=True, default="", max_length=300)),
                (
                    "provenance",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("promised_ev", models.FloatField(null=True)),
                ("promised_n", models.IntegerField(null=True)),
                ("shrinkage_lo", models.FloatField(default=0.35, null=True)),
                ("shrinkage_hi", models.FloatField(default=0.5, null=True)),
            ],
            options={
                "unique_together": {("model_id", "version")},
            },
        ),
        migrations.CreateModel(
            name="PairStrategyCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("pair", models.CharField(max_length=12)),
                ("strategy", models.CharField(max_length=60)),
                ("n", models.IntegerField(default=0)),
                ("ev", models.FloatField(null=True)),
                ("win_rate", models.FloatField(null=True)),
                ("context", models.JSONField(default=dict)),
            ],
            options={
                "unique_together": {("pair", "strategy")},
            },
        ),
        migrations.CreateModel(
            name="StrategyPerf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("strategy", models.CharField(max_length=40)),
                ("period", models.CharField(max_length=10)),
                ("n_trades", models.IntegerField(default=0)),
                ("net_r", models.FloatField(null=True)),
                ("win_rate", models.FloatField(null=True)),
                ("expectancy_r", models.FloatField(null=True)),
                ("profit_factor", models.FloatField(null=True)),
                ("max_dd_r", models.FloatField(null=True)),
                ("mode", models.CharField(default="paper", max_length=10)),
            ],
            options={
                "unique_together": {("strategy", "period", "mode")},
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=60)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "model_id")},
            },
        ),
        migrations.CreateModel(
            name="DecisionTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("seq", models.IntegerField(default=0)),
                ("stage", models.CharField(max_length=30)),
                ("record_id", models.CharField(max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="monitor.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["trade_id", "seq"],
                "unique_together": {("record_id", "stage", "seq")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="artifact path / commit ya chanzo", max_length=400
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="demo fixture (SI data halisi)"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("rule", models.CharField(max_length=80)),
                ("passed", models.BooleanField()),
                ("detail", models.CharField(blank=True, default="", max_length=300)),
                (
                    "trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="monitor.trade",
                    ),
                ),
            ],
            options={
                "unique_together": {("trade", "rule")},
            },
        ),
    ]
