# Generated by Django 5.2.16 on 2026-07-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="ts",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="vpsheartbeat",
            name="ts",
            field=models.DateTimeField(null=True),
        ),
    ]
